lib/railway_ui_web/router.ex
defmodule RailwayUiWeb.Router do
  use RailwayUiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RailwayUiWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/published_messages", PublishedMessageController, :index
    post "/published_messages/republish", PublishedMessageController, :republish
    get "/consumed_messages", ConsumedMessageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RailwayUiWeb do
  #   pipe_through :api
  # end
end

lib/railway_ui_web/views/layout_view.ex
defmodule RailwayUiWeb.LayoutView do
  use RailwayUiWeb, :view
end

lib/railway_ui_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RailwayUi</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <nav role="navigation" class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link "Railway IPC UI 🚂", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <%= link "published messages", to: Routes.published_message_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "consumed messages", to: Routes.consumed_message_path(@conn, :index), class: "nav-link" %>
            </li>
          </ul>
        </nav>
    </header>
    <main role="main" class="container">
      <%= Enum.map(get_flash(@conn), fn {flash_key, flash_message} -> %>
        <%= if flash_key == "error" do %>
          <p class="alert alert-dismissible fade show alert-danger"><%= flash_message %>
        <% else %>
          <p class="alert alert-dismissible fade show alert-success"><%= flash_message %>
        <% end %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
     <% end) %>
     <div class="container pt-5">
       <%= @inner_content %>
     </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>